/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.github.sarxos.java-conventions")
}

dependencies {
    api(project(":webcam-capture"))
    api(libs.com.sun.xml.bind.jaxb.core)
    api(libs.com.sun.xml.bind.jaxb.impl)
    api(libs.javax.xml.bind.jaxb.api)
    api(libs.org.apache.httpcomponents.httpclient)
    api(libs.org.apache.httpcomponents.httpmime)
    testImplementation(libs.junit.junit)
}

description = "Webcam Capture - IP Camera Driver"
