/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.github.sarxos.java-conventions")
}

dependencies {
    api(project(":webcam-capture"))
    testImplementation(libs.junit.junit)
    compileOnly(libs.ch.qos.logback.logback.classic)
}

description = "Webcam Capture - MJPEG Stream Capture Driver"
