/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.github.sarxos.java-conventions")
}

dependencies {
    api(libs.com.github.sarxos.v4l4j)
    api(project(":webcam-capture"))
}

description = "Webcam Capture - V4L4J Driver"
