/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.github.sarxos.java-conventions")
}

dependencies {
    api(project(":webcam-capture"))
    api(libs.commons.cli.commons.cli)
    api(libs.uk.co.caprica.picam)
    testImplementation(libs.commons.io.commons.io)
    testImplementation(libs.junit.junit)
    compileOnly(libs.ch.qos.logback.logback.classic)
}

description = "Webcam Capture - Raspberry Pi camera Driver"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
