/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.github.sarxos.java-conventions")
}

dependencies {
    api(project(":webcam-capture"))
    api(libs.net.java.dev.jna.jna)
    api(libs.org.freedesktop.gstreamer.gst1.java.core)
    testImplementation(libs.junit.junit)
    compileOnly(libs.ch.qos.logback.logback.classic)
}

description = "Webcam Capture - GStreamer 1.x Driver"
