/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.github.sarxos.java-conventions")
}

dependencies {
    api(libs.com.nativelibs4java.bridj)
    api(libs.org.slf4j.slf4j.api)
    testImplementation(libs.com.jayway.awaitility.awaitility)
    testImplementation(libs.junit.junit)
    testImplementation(libs.org.assertj.assertj.core)
    testImplementation(libs.org.easymock.easymock)
    compileOnly(libs.ch.qos.logback.logback.classic)
}

description = "Webcam Capture"
