/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.github.sarxos.java-conventions")
}

dependencies {
    api(project(":webcam-capture"))
    api(libs.org.bytedeco.javacv.platform)
}

description = "Webcam Capture - JavaCV Driver"
